apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: p3x-claim0
  name: p3x-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: p3x-pod
  labels:
    app: redis-p3x
spec:
  containers:
    - name: p3x
      image: patrikx3/p3x-redis-ui:latest
      ports:
        - containerPort: 7843
      volumeMounts:
        - mountPath: /settings
          name: p3x-claim0
  volumes:
    - name: p3x-claim0
      persistentVolumeClaim:
        claimName: p3x-claim0
        
---
apiVersion: v1
kind: Service
metadata:
    name: p3x-svc-lb
spec:
    type: LoadBalancer
    selector:
        app: redis-p3x
    ports:
    -   port: 7843
        targetPort: 7843
